---
- hosts: routers
  gather_facts: no
  connection: local
  vars:
    ansible_network_os: ios
  tasks:
    - name: GigabitEthernet1 interface up
      net_interface:
        name: GigabitEthernet1
        state: up
      register: test1
      ignore_errors: yes

    - name: Tunnel0 interface up
      net_interface:
        name: Tunnel0
        state: up
      register: test2
      ignore_errors: yes

    - name: Test reachability across tunnel rtr1->rtr2
      net_ping:
        dest: "10.0.0.2"
      when: inventory_hostname == "rtr1"
      register: test3
      ignore_errors: yes

    - name: Test reachability across tunnel rtr2->rtr1
      net_ping:
        dest: "10.0.0.1"
      when: inventory_hostname == "rtr2"
      register: test4
      ignore_errors: yes

    - name: Test reachability to ansible
      net_ping:
        dest: "{{hostvars['ansible']['private_ip']}}"
      register: test5
      ignore_errors: yes

    - name: Test reachability to host1
      net_ping:
        dest: "{{hostvars['host1']['private_ip']}}"
      register: test6
      ignore_errors: yes

    - name: create HTML report
      template:
        src: report.j2
        dest: ./generated_report.html
      delegate_to: localhost
      run_once: true
      ignore_errors: yes

    - name: debug outputs
      debug:
        var: "{{item}}"
      with_items:
        - test1
        - test2
        - test3
        - test4
        - test5
        - test6
